[test-repo]
owner = "sjeohp"
matrix_room_id = "!ZXvnxSiXstTeRmkMGk:matrix.parity.io"
whitelist = []

[some project]
owner = "sjeohp"
matrix_room_id = "!ZXvnxSiXstTeRmkMGk:matrix.parity.io"
whitelist = []
