version: 2
jobs:
  build:
    docker:
      - image: rust:latest

    steps:
      - run: apt-get update && apt-get install llvm clang librocksdb-dev -y
      - checkout
      - run: rustup component add rustfmt
      - run:
          name: Environment Variable Setup
          # rust-rocksdb by default tries to build from source which causes
          # a lot of issues. So we just use the one from `apt-get` and tell
          # rocksdb to use the system libraries.
          command: |
              echo 'export ROCKSDB_LIB_DIR="/usr/lib"' >> $BASH_ENV
              echo 'export ROCKSDB_STATIC=1' >> $BASH_ENV
      - run:
          name: Checking
          command: cargo fmt --all -- --check
      - run:
          name: Building
          command: cargo build --all
      - run:
          name: Testing
          command: cargo test --all
